#!/bin/bash
set -e;

# Check if name is specified
if [[ $1 == sync:* ]]; then
    if [[ -z $2 ]]; then
        echo "You must specify an app name"
        exit 1
    else
        APP="$2"
        # Check if app exists with the same name
        if [[ -d "$DOKKU_ROOT/$APP" ]]; then
            APP_EXISTS=true
        else
            APP_EXISTS=false
        fi
    fi
fi

# Create files directory if does not exist
if [[ ! -d $DOKKU_ROOT/$APP/files ]]; then
    mkdir -p $DOKKU_ROOT/$APP/files
    chown -R dokku: $DOKKU_ROOT/$APP/files
fi

case "$1" in

  sync:up)
    #take tared files from std in and untar them into app/file
    tar xfvm - -C $DOKKU_ROOT/$APP/files
  ;;
  sync:down)
    #tar files folder and output to stdout
   cd $DOKKU_ROOT/$APP/files 
   tar cfm - ./*
  ;;

  help)
    cat && cat<<EOF
    sync:up <app>        imports a tar pipe into files folder
    sync:down <app>      exports a tar pipe from files folder 

EOF
    ;;

esac
